In [11]:
import torch
import numpy as np
import pandas as pd

<h1>Tensores</h1>

In [3]:
torch.__version__

'1.3.1'

In [5]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [8]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[-1.6516e+04,  4.5745e-41],
        [-1.6520e+04,  4.5745e-41]])


tensor([[0.4957, 0.9764],
        [0.7145, 0.5755]])

In [10]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.2750, 0.4982],
        [0.9760, 0.5918]])

In [11]:
result = tensor_b + tensor_c
result

tensor([[0.7707, 1.4746],
        [1.6904, 1.1673]])

In [13]:
result.shape
reshaped = result.view(1,4)
reshaped

tensor([[0.7707, 1.4746, 1.6904, 1.1673]])

In [19]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [20]:
points, points.stride()


(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [21]:
p_t = points.t()
p_t , p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [24]:
tensor_x = torch.tensor([1,2,3,4])
#tensor_x, torch.unsqueeze(tensor_x,0)
tensor_x, torch.unsqueeze(tensor_x,1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [3]:
numpyArray = np.random.randn(2 , 2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy


tensor([[ 1.1209, -0.5664],
        [-0.7441, -0.2416]], dtype=torch.float64)

<h1>Representar datos con tensores</h1>


In [5]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 1.1209, -0.5664],
        [-0.7441, -0.2416]], dtype=torch.float64)
tensor(-0.1078, dtype=torch.float64)
tensor([ 0.1884, -0.4040], dtype=torch.float64)
tensor([ 0.2772, -0.4928], dtype=torch.float64)


In [6]:
#Desviacion estandar
torch.std(from_numpy, dim=1)

tensor([1.1931, 0.3553], dtype=torch.float64)

In [7]:
torch.save(from_numpy, 'tensor.t')

In [10]:
load = torch.load('tensor.t')
load

tensor([[ 1.1209, -0.5664],
        [-0.7441, -0.2416]], dtype=torch.float64)

In [13]:
url = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31   
1               1   20801   Cristiano Ronaldo   33   
2               2  190871           Neymar Jr   26   
3               3  193080              De Gea   27   
4               4  192985        K. De Bruyne   27   
...           ...     ...                 ...  ...   
18202       18202  238813        J. Lundstram   19   
18203       18203  243165  N. Christoffersson   19   
18204       18204  241638           B. Worman   16   
18205       18205  246268      D. Walker-Rice   17   
18206       18206  246269           G. Nugent   16   

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium   
...                                               ...         ...   
18202  https://cdn.sofifa.org/players/4/19/238813.png     England   
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden   
18204  https://cdn.sofifa.org/players/4/19/241638.png     England   
18205  https://cdn.sofifa.org/players/4/19/246268.png     England   
18206  https://cdn.sofifa.org/players/4/19/246269.png     England   

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png       94         94   
1      https://cdn.sofifa.org/flags/38.png       94         94   
2      https://cdn.sofifa.org/flags/54.png       92         93   
3      https://cdn.sofifa.org/flags/45.png       91         93   
4       https://cdn.sofifa.org/flags/7.png       91         92   
...                                    ...      ...        ...   
18202  https://cdn.sofifa.org/flags/14.png       47         65   
18203  https://cdn.sofifa.org/flags/46.png       47         63   
18204  https://cdn.sofifa.org/flags/14.png       47         67   
18205  https://cdn.sofifa.org/flags/14.png       47         66   
18206  https://cdn.sofifa.org/flags/14.png       46         66   

                      Club  ... Composure Marking StandingTackle  \
0             FC Barcelona  ...      96.0    33.0           28.0   
1                 Juventus  ...      95.0    28.0           31.0   
2      Paris Saint-Germain  ...      94.0    27.0           24.0   
3        Manchester United  ...      68.0    15.0           21.0   
4          Manchester City  ...      88.0    68.0           58.0   
...                    ...  ...       ...     ...            ...   
18202      Crewe Alexandra  ...      45.0    40.0           48.0   
18203       Trelleborgs FF  ...      42.0    22.0           15.0   
18204     Cambridge United  ...      41.0    32.0           13.0   
18205      Tranmere Rovers  ...      46.0    20.0           25.0   
18206      Tranmere Rovers  ...      43.0    40.0           43.0   

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning  \
0               26.0      6.0        11.0       15.0           14.0   
1               23.0      7.0        11.0       15.0           14.0   
2               33.0      9.0         9.0       15.0           15.0   
3               13.0     90.0        85.0       87.0           88.0   
4               51.0     15.0        13.0        5.0           10.0   
...              ...      ...         ...        ...            ...   
18202           47.0     10.0        13.0        7.0            8.0   
18203           19.0     10.0         9.0        9.0            5.0   
18204           11.0      6.0         5.0       10.0            6.0   
18205           27.0     14.0         6.0       14.0            8.0   
18206           50.0     10.0        15.0        9.0           12.0   

      GKReflexes Release Clause  
0            8.0        €226.5M 

In [15]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [21]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [22]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [23]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [24]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [28]:
std = torch.std(data , dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [29]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [32]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target , 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

# goodMean, averageMean, notSoGoodMean

for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
    print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
